const USER_LOGIN = "USER_LOGIN";
const USER_SIGNUP = "USER_SIGNUP";
const USER_LOCATION = "USER_LOCATION";
const USER_STATUS = "USER_STATUS";

export { USER_SIGNUP, USER_LOGIN, USER_LOCATION, USER_STATUS };
