const USER_LOGIN = "USER_LOGIN";
const USER_SIGNUP = "USER_SIGNUP";
const USER_LOCATION = "USER_LOCATION";
const USER_STATUS = "USER_STATUS";
const USER_DEVICE_TOKEN = "USER_DEVICE_TOKEN";

export {
	USER_SIGNUP,
	USER_LOGIN,
	USER_LOCATION,
	USER_STATUS,
	USER_DEVICE_TOKEN,
};
